### PR TITLE
fix build url redirection from Jenkins to Splunk

### PR DESCRIPTION
**Pull request by mifitous**
- JENKINS-62821 Splunk Plugin "build_analysis" Path In Jobs Not Directing To The Correct Path To "Splunk App For Jenkins"
- 
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by mifitous** [comment]
@fengxx : Can you please approve and merge?

**Comment by fengxx** [comment]
thanks for contributing, could you please split the changes into two commits
1) update styles only (such as indent, formatting)
2) new feature
in the long run, it helps triaging issues by comparing commit diff

**Comment by fengxx** [comment]
I think style config xml is optioned  (`.idea` `.mvn` files), checking them into git may cause unnecessary formatting changes in the future if  source codes were touched (e.g. files were formatted by indent 120 but new style is 100), could we avoid committing them into git?

**Comment by mifitous** [comment]
Hi @fengxx
will do

**Pull request closed without merging**
